<?php

const MODULE_INVITE = 1;
const MODULE_MEMBERS_LIST = 1;
const MODULE_INVITE_ACTIVITY = 1;
const INVITE_CODE_OPTION = 'may';
const INVITE_CODE_EXPIRE = 14;
const INVITE_CODE_LIMIT = 0;
const INVITE_CODE_USERNAME = 1;
const INVITE_CODE_LENGTH = 0;
const INVITE_CODE_LIMIT_UNUSED = 0;
const INVITE_EMAIL_LIMIT = 3;
const INVITE_EMAIL_TIME = 14;
const INVITE_DISPLAY_MESSAGE_SIDEBAR = 1;
const INVITE_DISPLAY_USERINFORMATION = 1;
const INVITE_DISPLAY_BOX_ENTRIES = 5;
